# Site settings
baseURL = ""
languageCode = "en-US"
title = "Hi, i'm Richard!"
theme = "steinbrueckri"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-130028619-1"

# Copyright
copyright = "Richard Steinbrück"

[params]

  # Gallery Settings
  ## Highest width is 2500px for landscape and 1500px for portrait.
  ## This will give both orientations roughly the same resolution and size.
  ## Every landscape image will also be scaled down to 1500px and 1000px,
  ## and portrait photos to 1000px and 750px wide.
  landscapePhotoWidths = [2500, 1500, 1000, 500, 250]
  portraitPhotoWidths = [1500, 1000, 750, 500, 250]

  DateForm = "02.01.2006"

  # Metadata for search engines and social sharing
  author = "Richard Steinbrück"
  author_image = "images/me.jpg"
  tagline = "tagline"
  description = "My Blog"
  shareImage = "images/me.jpg"
  twitterHandle = "z3rogate"

  # Favicon
  favicon = "favicon.ico"

  # Frontpage
  frontpage_image = "images/frontpage.jpg"
  frontpage_caption_name = "Richard Steinbrück"
  frontpage_caption_email = "me@steinbrueck.io"
  frontpage_caption_url = "steinbrueck.io"

## Menu ##############################################################################
[[menu.main]]
name = "Home"
url  = "/"
weight = 10

[[menu.main]]
name = "Blog"
url  = "/blog"
weight = 12

[[menu.main]]
name = "Gallery"
url  = "/gallery"
weight = 13

[[menu.main]]
name = "About"
url  = "/page/about"
weight = 88

[[menu.main]]
name = "Contact"
url  = "/page/contact/"
weight = 99